import React from "react";
import Head from "next/head";
type Props = {};

const Blogs = (props: Props) => {
  return (
    <div className="bg-custom-light  overflow-hidden w-screen h-screen">
      <Head>
        <title>Hashir Nouman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-52 ml-12 flex-col space-y-6 ">
        <h1 className="text-9xl font-bold text-custom-lightest py-5 ">
          Coming Soon...
        </h1>
      </div>
    </div>
  );
};

export default Blogs;
