import type { NextPage } from "next";
import Head from "next/head";
import { Linkedin } from "react-feather";

const Home: NextPage = () => {
  return (
    <div className="bg-custom-light  overflow-hidden w-screen h-screen">
      <Head>
        <title>Hashir Nouman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-52 ml-12 flex-col space-y-6">
        <h1 className="text-7xl font-bold text-custom-lightest ">Hi There,</h1>
        <h1 className="text-7xl font-bold text-custom-lightest ">
          I am <span className="text-custom">Hashir Nouman</span>
        </h1>
        <h1 className="text-7xl text-custom font-bold">Full Stack Developer</h1>
        <h1 className="text-5xl text-custom font-bold py-2">
          React,Typescript, Next.js
        </h1>
      </div>
    </div>
  );
};

export default Home;
